### ISSUE TITLE
ERROR: Failed building wheel for instagram-scraper

### ISSUE THREAD

**Issue by GreenAA** [darkrequests/darkinsta#1]
`pip install instagram-scraper
Defaulting to user installation because normal site-packages is not writeable
Collecting instagram-scraper
  Using cached instagram-scraper-66.0.3.tar.gz (1.2 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: instagram-scraper
  Building wheel for instagram-scraper (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      C:\Users\777da\AppData\Roaming\Python\Python312\site-packages\setuptools\_distutils\dist.py:266: UserWarning: Unknown distribution option: 'readme'
        warnings.warn(msg)
      running bdist_wheel
      running build
      C:\Users\777da\AppData\Roaming\Python\Python312\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
`

**Comment by darkrequests** [comment]
I have fixed the code,removing the module

**Comment by GreenAA** [comment]
thank you king , perfect .

**Comment by darkrequests** [comment]
> thank you king , perfect .

try the new update and tell me what to add
